In [2]:
import cv2

### Read Image

In [2]:
# Read BGR
img = cv2.imread("14_OpenCV_1.jpg", 1)
print(type(img))
print(img)
print(img.shape)

<class 'numpy.ndarray'>
[[[239 240 238]
  [240 241 239]
  [240 241 239]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[242 243 241]
  [242 243 241]
  [242 243 241]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[244 245 243]
  [244 245 243]
  [244 245 243]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
(2040, 1360, 3)
**********


In [3]:
# Read Grayscale
img = cv2.imread("14_OpenCV_1.jpg", 0)
print(type(img))
print(img)
print(img.shape)

<class 'numpy.ndarray'>
[[239 240 240 ... 255 255 255]
 [242 242 242 ... 255 255 255]
 [244 244 244 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
(2040, 1360)


### Show Image

In [5]:
img = cv2.imread("14_OpenCV_1.jpg", 1)
cv2.imshow("Image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Resize Image

In [6]:
img = cv2.imread("14_OpenCV_1.jpg", 1)
res_img = cv2.resize(img, (100, 50))
cv2.imshow("Res_Image", res_img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [7]:
res_img = cv2.resize(img, (img.shape[1] // 4, img.shape[0] // 4))
cv2.imshow("Res_Image", res_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Face Detect

In [10]:
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
img = cv2.imread("14_OpenCV_1.jpg")
# Grayscaling a BGR colored image
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
faces = face_cascade.detectMultiScale(gray_img, scaleFactor=1.05, minNeighbors=5)

print(type(faces))
print(faces)

for x, y, w, h in faces:
    img = cv2.rectangle(img, (x, y), (x + w, y + h), (0, 0, 255), 3)

resized = cv2.resize(img, (img.shape[1] // 4, img.shape[0] // 4))

cv2.imshow("Gray", resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

<class 'numpy.ndarray'>
[[ 424  261  529  529]
 [ 232 1424  501  501]]


### Video 1st Frame Capture

In [11]:
video = cv2.VideoCapture(0)
check, frame = video.read()
print(check)
print(frame)
# time.sleep(3)
cv2.imshow("Capturing", frame)
cv2.waitKey(0)
video.release()
cv2.destroyAllWindows()

True
[[[250 167 168]
  [255 180 181]
  [254 199 192]
  ...
  [ 28   5  16]
  [ 23   8  16]
  [ 23   8  16]]

 [[242 200 202]
  [239 198 200]
  [244 202 197]
  ...
  [ 26   5  16]
  [ 24   6  16]
  [ 25   7  18]]

 [[236 182 180]
  [237 183 181]
  [235 190 180]
  ...
  [ 28   5  18]
  [ 24   6  16]
  [ 24   6  16]]

 ...

 [[ 86  78  90]
  [ 86  78  90]
  [ 93  75  95]
  ...
  [ 26  30   9]
  [ 23  32  11]
  [ 23  32  11]]

 [[ 89  79  93]
  [ 87  76  91]
  [ 95  73 100]
  ...
  [ 27  29   8]
  [ 23  31   9]
  [ 22  29   8]]

 [[ 87  78  87]
  [ 87  78  87]
  [ 93  73 100]
  ...
  [ 30  26  13]
  [ 27  29   8]
  [ 27  29   8]]]


### Video Capture in Loop

In [14]:
video = cv2.VideoCapture(0)
a = 1
while True:
    a += 1
    check, frame = video.read()
    # print("#" * 20)
    # print(check)
    # print(frame)

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    cv2.imshow("Capturing", gray)
    key = cv2.waitKey(1)
    if key == ord('q'):
        break
print(a)
video.release()
cv2.destroyAllWindows()

150


### Face Detection from Video in Loop

In [17]:
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
video = cv2.VideoCapture(0)
a = 1
while True:
    a += 1
    check, frame = video.read()
    # print("#" * 20)
    # print("Check : ", check)
    # print("FRAME : ")
    # print(frame)
    faces = face_cascade.detectMultiScale(frame, scaleFactor=1.05, minNeighbors=5)
    # print("FACE : ")
    # print(faces)

    for x, y, w, h in faces:
        frame = cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 3)

    resized = cv2.resize(frame, (frame.shape[1], frame.shape[0]))
    cv2.imshow("Capturing", resized)
    key = cv2.waitKey(1)
    if key == ord('q'):
        break
print(a)
video.release()
cv2.destroyAllWindows()

26


### Motion Detector

In [5]:
# import pandas as pd
# from datetime import datetime

first_frame = None

# status_list = [None, None]
# times = []
# df = pd.DataFrame(columns=["Start", "End"])

video = cv2.VideoCapture(0)
while True:
    check, frame = video.read()

    # status = 0

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    gray = cv2.GaussianBlur(gray, (21, 21), 0)
    if first_frame is None:
        first_frame = gray
        continue
    delta_frame = cv2.absdiff(first_frame, gray)
    thresh_delta = cv2.threshold(delta_frame, 30, 255, cv2.THRESH_BINARY)[1]
    thresh_delta = cv2.dilate(thresh_delta, None, iterations=0)
    major = cv2.__version__.split('.')[0]
    if major == '3':
        ret, contours, hierarchy = cv2.findContours(thresh_delta.copy(),
                                                    cv2.RETR_EXTERNAL,
                                                    cv2.CHAIN_APPROX_SIMPLE)
    else:
        contours, hierarchy = cv2.findContours(thresh_delta.copy(),
                                                   cv2.RETR_EXTERNAL,
                                                   cv2.CHAIN_APPROX_SIMPLE)
    for contour in contours:
        if cv2.contourArea(contour) < 1000:
            continue

        # status = 1
        
        (x, y, w, h) = cv2.boundingRect(contour)
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 3)

    # status_list.append(status)
    # status_list = status_list[-2:]
    # if status_list[-1] == 1 and status_list[-2] == 0:
        # times.append(datetime.now().time())
    # if status_list[-1] == 0 and status_list[-2] == 1:
        # times.append(datetime.now().time())
    
    frame = cv2.resize(frame, (frame.shape[1] // 2, frame.shape[0] // 2))
    cv2.imshow("Frame", frame)
    gray = cv2.resize(gray, (gray.shape[1] // 2, gray.shape[0] // 2))
    cv2.imshow("Capturing", gray)
    delta_frame = cv2.resize(delta_frame, (delta_frame.shape[1] // 2, delta_frame.shape[0] // 2))
    cv2.imshow("Delta", delta_frame)
    thresh_delta = cv2.resize(thresh_delta, (thresh_delta.shape[1] // 2, thresh_delta.shape[0] // 2))
    cv2.imshow("Thresh", thresh_delta)

    key = cv2.waitKey(1)
    if key == ord('q'):
        break

# print(status_list)
# print(times)
# for i in range(0, len(times), 2):
    # df = df.append({"Start": times[i], "End": times[i+1]}, ignore_index=True)
# df.to_csv("14_OpenCV.csv")

video.release()
cv2.destroyAllWindows()